
language: csharp
solution: DDDPizza.sln
install:
- nuget restore DDDPizza.sln
script:
- xbuild /p:Configuration=Release DDDPizza.sln
- mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DDDPizza.UnitTests/bin/Release/DDDPizza.UnitTests.dll
