# build Configuration, i.e. Debug, Release, etc.
configuration: Release

environment:
  COVERALLS_REPO_TOKEN:
    secure: 6TXz6Xxq2Za0nfSUw95F7vmUwpMTsRC5Y

before_build:
  - nuget restore

install:
  - npm install -g bower karma karma-cli karma-phantomjs-launcher karma-coverage karma-jasmine karma-chrome-launcher karma-mocha karma-sinon karma-chai-sinon karma-chai
  - bower install

test_script: 
  - npm run test-single-run
  - nunit-console.exe "DDDPizza.UnitTests\bin\Release\DDDPizza.UnitTests.dll"

build:
  verbosity: minimal

cache:
  - node_modules 
