# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - nuget restore
  - karma start karma.conf.js  --single-run
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global bower
  - npm install --production
  - npm install each-exec require-bower-files script-equal tape
  - bower install

build:
  verbosity: minimal
