# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - nuget restore

install:
  - npm install -g node-inspector bower gulp typescript tsd phantomjs tslint karma karma-cli
  - npm install --production
  - npm install each-exec require-bower-files script-equal tape
  - bower install
  - karma start karma.conf.js  --single-run

build:
  verbosity: minimal

cache:
  - packages -> **\packages.config