# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - nuget restore

install:
  - npm install -g bower karma karma-cli karma-phantomjs-launcher karma-coverage karma-jasmine karma-chrome-launcher karma-mocha karma-sinon karma-chai-sinon karma-chai
  - bower install

test_script: 
  - npm run test-single-run
  - bin\Release\nunit-console DDDPizza.UnitTests --config=Release

build:
  verbosity: minimal

cache:
  - node_modules 
