# build Configuration, i.e. Debug, Release, etc.
configuration: Release

environment:
  COVERALLS_REPO_TOKEN:
    secure: 6TXz6Xxq2Za0nfSUw95F7vmUwpMTsRC5Y

before_build:
  - nuget restore "DDDPizza.sln"

install:
  - npm install -g bower karma karma-cli karma-phantomjs-launcher karma-coverage karma-jasmine karma-chrome-launcher karma-mocha karma-sinon karma-chai-sinon karma-chai
  - bower install

test_script: 
#  - npm run test-single-run
  - nunit-console.exe "DDDPizza.UnitTests\bin\Release\DDDPizza.UnitTests.dll"
  - OpenCover.Console.exe -register:user -target:"nunit-console.exe" -targetargs:"""DDDPizza.UnitTests\bin\Release\DDDPizza.UnitTests.dll"" /noshadow" -output:opencovertests.xml -returntargetcode -filter:"+[DDDPizza.DomainModels]*" -excludebyattribute:*.ExcludeFromCodeCoverage*  
  - ps: .\packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover -i opencovertests.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
  
build:
  verbosity: minimal
  project: DDDPizza.sln

cache:
  - node_modules 
  - packages
