# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - nuget restore

install:
  - npm install -g node-inspector bower gulp phantomjs karma karma-cli karma-jasmine 
  - npm install --production
  - npm install each-exec require-bower-files script-equal tape
  - bower install

test_script: 
  - npm run test-single-run

build:
  verbosity: minimal
